<?php

namespace Database\Seeders;

use App\Models\MembershipType;
use Illuminate\Database\Seeder;

class MembershipTypeSeeder extends Seeder
{
    public function run(): void
    {
        $types = [
            [
                'key' => 'a',
                'name' => 'A-lid',
                'description' => 'Roeiend lid vanaf 21 jaar met volledige rechten: botengebruik, instructie geven en 3× per jaar introducees meenemen.',
                'min_age' => 21,
                'max_age' => null,
                'allows_boat_use' => true,
                'allows_instruction' => true,
                'intro_per_year' => 3,
                'allows_competition' => true,
                'seasonal_only' => false,
                'auto_expiry' => false,
                'requires_proof' => false,
                'is_partner_type' => false,
                'derives_from_key' => null,
                'sort_order' => 10,
            ],
            [
                'key' => 'b',
                'name' => 'B-lid',
                'description' => 'Roeiend lid vanaf 21 jaar met botengebruik en 3× per jaar introducees, zonder instructiebevoegdheid.',
                'min_age' => 21,
                'max_age' => null,
                'allows_boat_use' => true,
                'allows_instruction' => false,
                'intro_per_year' => 3,
                'allows_competition' => true,
                'seasonal_only' => false,
                'auto_expiry' => false,
                'requires_proof' => false,
                'is_partner_type' => false,
                'derives_from_key' => null,
                'sort_order' => 20,
            ],
            [
                'key' => 'gezins_a',
                'name' => 'Gezins-/partnerlid A',
                'description' => 'Partner van een A-lid (huwelijk of gezamenlijk adres); zelfde rechten als een A-lid.',
                'min_age' => 21,
                'max_age' => null,
                'allows_boat_use' => true,
                'allows_instruction' => true,
                'intro_per_year' => 3,
                'allows_competition' => true,
                'seasonal_only' => false,
                'auto_expiry' => false,
                'requires_proof' => false,
                'is_partner_type' => true,
                'derives_from_key' => 'a',
                'sort_order' => 30,
            ],
            [
                'key' => 'gezins_b',
                'name' => 'Gezins-/partnerlid B',
                'description' => 'Partner van een B-lid; zelfde rechten als een B-lid.',
                'min_age' => 21,
                'max_age' => null,
                'allows_boat_use' => true,
                'allows_instruction' => false,
                'intro_per_year' => 3,
                'allows_competition' => true,
                'seasonal_only' => false,
                'auto_expiry' => false,
                'requires_proof' => false,
                'is_partner_type' => true,
                'derives_from_key' => 'b',
                'sort_order' => 40,
            ],
            [
                'key' => 'jeugd',
                'name' => 'Jeugdlid',
                'description' => 'Jongere van 12 tot en met 20 jaar; botengebruik toegestaan.',
                'min_age' => 12,
                'max_age' => 20,
                'allows_boat_use' => true,
                'allows_instruction' => false,
                'intro_per_year' => 0,
                'allows_competition' => true,
                'seasonal_only' => false,
                'auto_expiry' => false,
                'requires_proof' => false,
                'is_partner_type' => false,
                'derives_from_key' => null,
                'sort_order' => 50,
            ],
            [
                'key' => 'student',
                'name' => 'Studentlid',
                'description' => 'Student met rechten van een A-lid. Vereist geldig studentbewijs (OV-studentenkaart en studentenpas). Geldig per kalenderjaar; vervalt automatisch tenzij verlengd vóór 1 november.',
                'min_age' => null,
                'max_age' => null,
                'allows_boat_use' => true,
                'allows_instruction' => true,
                'intro_per_year' => 3,
                'allows_competition' => true,
                'seasonal_only' => false,
                'auto_expiry' => true,
                'requires_proof' => true,
                'is_partner_type' => false,
                'derives_from_key' => null,
                'sort_order' => 60,
            ],
            [
                'key' => 'buitenstudent',
                'name' => 'Buitenstudentlid',
                'description' => 'Student van 21 tot en met 26 jaar, met studentbewijs; botengebruik alleen in de zomerschoolvakantie; geen wedstrijden.',
                'min_age' => 21,
                'max_age' => 26,
                'allows_boat_use' => true,
                'allows_instruction' => false,
                'intro_per_year' => 0,
                'allows_competition' => false,
                'seasonal_only' => true,
                'auto_expiry' => true,
                'requires_proof' => true,
                'is_partner_type' => false,
                'derives_from_key' => null,
                'sort_order' => 70,
            ],
            [
                'key' => 'aspirant',
                'name' => 'Aspirantlid',
                'description' => 'Jonger dan 12 jaar; wordt jeugdlid bij aanvang van het verenigingsjaar waarin men leerling van minimaal groep 4 wordt.',
                'min_age' => null,
                'max_age' => 11,
                'allows_boat_use' => false,
                'allows_instruction' => false,
                'intro_per_year' => 0,
                'allows_competition' => false,
                'seasonal_only' => false,
                'auto_expiry' => false,
                'requires_proof' => false,
                'is_partner_type' => false,
                'derives_from_key' => null,
                'sort_order' => 80,
            ],
            [
                'key' => 'societeit',
                'name' => 'Sociëteitslid',
                'description' => 'Alleen toegang tot de sociëteit; geen botengebruik.',
                'min_age' => null,
                'max_age' => null,
                'allows_boat_use' => false,
                'allows_instruction' => false,
                'intro_per_year' => 0,
                'allows_competition' => false,
                'seasonal_only' => false,
                'auto_expiry' => false,
                'requires_proof' => false,
                'is_partner_type' => false,
                'derives_from_key' => null,
                'sort_order' => 90,
            ],
        ];

        foreach ($types as $type) {
            MembershipType::updateOrCreate(['key' => $type['key']], $type);
        }
    }
}
